platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'MeetApp' do
  # Pods for MeetApp

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  use_unimodules!

  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  # pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'MeetAppTests' do
    inherit! :search_paths
  end
end
